# Build NodePropertyPalette using latest VS and DotNET
# To be updated
name: NodePropertyPalette-Build
on: [push]
jobs:
 build:
  runs-on: windows-latest
  steps:
    - name: Checkout NodePropertyPalette Repo
      uses: actions/checkout@v2
      with:
        path: NodePropertyPalette
    - name: Checkout Dynamo Repo
      uses: actions/checkout@v2
      with:
        path: Dynamo
        repository: DynamoDS/Dynamo
        ref: RC2.5.0_master
    - name: Setup Nuget.exe to use on VM
      uses: nuget/setup-nuget@v1
    - name: Nuget Restore in Dynamo solution
      run: nuget restore $Env:GITHUB_WORKSPACE\Dynamo\src\Dynamo.All.sln
    - name: Nuget Restore in NodePropertyPalette solution
      run: nuget restore $Env:GITHUB_WORKSPACE\NodePropertyPalette\NodePropertyPalette.sln
    - name: Build Dynamo with MSBuild
      run: |
        echo "***Execute ls, and you should see two folders created***"
        ls
        echo "***Continue with the build, Good luck developer!***"
        cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
           .\MSBuild.exe $Env:GITHUB_WORKSPACE\Dynamo\src\Dynamo.All.sln
    - name: Build NodePropertyPalette with DotNET
      run: |
        echo "***Building NodePropertyPalette now following Dynamo build***"
        cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
           .\MSBuild.exe $Env:GITHUB_WORKSPACE\NodePropertyPalette\NodePropertyPalette.sln
    # look for NodePropertyPalette
    - name: Find NodePropertyPalette
      run: |
        cd "$Env:GITHUB_WORKSPACE\NodePropertyPalette\NodePropertyPalette\bin\Debug"
        ls